"use client";
import {useQuery} from "@tanstack/react-query";
import {Filter,Plus,Search,SlidersHorizontal} from "lucide-react";
import {useState} from "react";
import {api} from "@/services/api";
import {useDebounce} from "@/hooks/use-debounce";
import {MeetingCard} from "./meeting-card";
import {CreateMeetingDialog} from "./meeting-dialog";

export function Dashboard(){const[q,setQ]=useState("");const[participant,setParticipant]=useState("");const[dateFrom,setDateFrom]=useState("");const[dateTo,setDateTo]=useState("");const[sort,setSort]=useState("recent");const[page,setPage]=useState(1);const[open,setOpen]=useState(false);const query=useDebounce(q);const person=useDebounce(participant);const params=new URLSearchParams({q:query,participant:person,date_from:dateFrom,date_to:dateTo,sort,page:String(page),page_size:"6"});const {data,isLoading,isError}=useQuery({queryKey:["meetings",query,person,dateFrom,dateTo,sort,page],queryFn:()=>api.meetings(params)});const pages=data?Math.max(1,Math.ceil(data.total/data.page_size)):1;const reset=()=>{setQ("");setParticipant("");setDateFrom("");setDateTo("");setSort("recent");setPage(1)};return <main className="content"><header className="page-head"><div><p className="eyebrow">YOUR WORKSPACE</p><h1>Meetings</h1><p className="subtle">Everything your team has discussed, organized and ready.</p></div><button onClick={()=>setOpen(true)} className="primary"><Plus size={18}/>New meeting</button></header><section className="toolbar"><label className="searchbox"><Search size={18}/><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Search meetings or people"/></label><label className="filter"><Filter size={16}/><input value={participant} onChange={e=>{setParticipant(e.target.value);setPage(1)}} placeholder="Filter person"/></label><label className="date-filter">From<input type="date" value={dateFrom} onChange={e=>{setDateFrom(e.target.value);setPage(1)}}/></label><label className="date-filter">To<input type="date" value={dateTo} min={dateFrom||undefined} onChange={e=>{setDateTo(e.target.value);setPage(1)}}/></label><label className="sort"><SlidersHorizontal size={16}/><select value={sort} onChange={e=>{setSort(e.target.value);setPage(1)}}><option value="recent">Most recent</option><option value="oldest">Oldest first</option><option value="title">Title A–Z</option></select></label>{(q||participant||dateFrom||dateTo||sort!=="recent")&&<button className="clear-filters" onClick={reset}>Clear</button>}</section>{isLoading&&<div className="empty">Loading your meeting library…</div>}{isError&&<div className="empty">We couldn’t load meetings. Check that the API is running.</div>}{data&&<><div className="library-meta"><b>{data.total} meetings</b><span>Showing page {data.page} of {pages}</span></div><div className="meeting-grid">{data.items.map(meeting=><MeetingCard meeting={meeting} key={meeting.id}/>)}</div>{!data.items.length&&<div className="empty">No meetings match that search.</div>}{pages>1&&<div className="pagination"><button className="secondary" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} of {pages}</span><button className="secondary" disabled={page===pages} onClick={()=>setPage(page+1)}>Next</button></div>}</>}<CreateMeetingDialog open={open} onClose={()=>setOpen(false)}/></main>}
